image:
  repository: tccr.io/truecharts/inventree
  tag: 0.9.0@sha256:b65b4a87c85d8151955834c293e7981b78cd56e88e195f80d58631df93b79d16
  pullPolicy: IfNotPresent

nginxImage:
  repository: tccr.io/truecharts/nginx
  tag: 1.23.3@sha256:89b30f1b0eecd4bd51a8b449503846c63cd85792bd3a14a7666a43c4dd8c0c82
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
# https://github.com/inventree/InvenTree/pull/3096
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envFrom:
  - secretRef:
      name: '{{ include "tc.common.names.fullname" . }}-inventree-secret'
  - configMapRef:
      name: '{{ include "tc.common.names.fullname" . }}-inventree-config'

inventree:
  credentials:
    admin_mail: "test@example.com"
    admin_user: "testuser"
    admin_password: "secret"
  general:
    debug: false
    log_level: "INFO"
    plugins_enabled: false
    login_confirm_days: 3
    login_attempts: 5
  mail:
    backend: "django.core.mail.backends.smtp.EmailBackend"
    host: ""
    port: 587
    username: ""
    password: ""
    tls: false
    ssl: false
    sender: ""

service:
  main:
    ports:
      main:
        port: 10231

persistence:
  data:
    enabled: true
    mountPath: "/home/inventree/data"
  inventree-nginx:
    enabled: true
    noMount: true
    type: custom
    mountPath: "/etc/nginx/conf.d"
    volumeSpec:
      configMap:
        name: '{{ include "tc.common.names.fullname" . }}-inventree-config-nginx'
        items:
          - key: nginx.conf
            path: default.conf

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: inventree
  postgresqlDatabase: inventree

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: default

portal:
  enabled: true
